name: Deployment With Multiple Jobs
on: push
jobs:
  prepare_code:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test_code:
    runs-on: ubuntu-latest
    needs: prepare_code
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test_code
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Create Build
        run: npm run build
      - name: Deploy
        run: |
          echo "Deploying build..."
          sleep 3
          echo "Deployed successfully."
