name: Deployment With Single Job
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test Code
        run: npm run test
      - name: Create Build
        run: npm run build
      - name: Deploy
        run: |
          echo "Deploying build..."
          sleep 3
          echo "Deployed successfully."
